controllers/QuestionController.php
<?php
namespace backend\controllers;

use Yii;
use common\models\database\Question;
use common\models\database\QuestionSearch;
use common\models\database\Answer;
use common\models\database\AnswerSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\db\Query;
use common\models\database\Gallery;

/**
 * QuestionController implements the CRUD actions for Question model.
 */
class QuestionController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                    'deleteanswer' => ['POST']
                ],
            ],
        ];
    }

    /**
     * Lists all Question models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new QuestionSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Question model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }   

    /**
     * Updates an existing Question model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            $searchModel = new AnswerSearch();
            $searchModel->question_id=$id;
            $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

            return $this->render('update', [
                'model' => $model,
                'all_types' =>$this->getQuestionTypes(),
                'id' => $model->getAttribute('test_id'), 
                'answers_model' =>$dataProvider,
            ]);
        }
    }
    
    /**
     * @param integer $id
     * @return mixed
     */
    public function actionTest($id)
    {
        $searchModel = new QuestionSearch();
        if(isset($id)){
            $searchModel->test_id=$id;
        }
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'id'=> $id
        ]);
    }

    /**
     * Deletes an existing Question model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
    */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $test_id = $model->getAttribute('test_id');
        $model->delete();
        return $this->redirect(['test', 'id'=>$test_id]);
    }

    /**
     * Deletes an existing Amswer model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
    */
    public function actionDeleteanswer($id)
    {
        if (($model = Answer::findOne($id)) !== null) {
            $question_id= $model->getAttribute('question_id');
            $model->delete();
            return $this->redirect(['update', 'id'=>$question_id]);
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Save All answers
     * @return mixed
    */
    public function actionSaveanswers($id)
    {
        $allAnswers=[];
        if(Yii::$app->request->post('Answer')){
//            print_r(Yii::$app->request->post('Answer'));die();
            $typeQuestion = Question::findOne(Yii::$app->request->post('Answer')[1]['question_id']);
            $validate_flag=true;
           foreach (Yii::$app->request->post('Answer') as $answer){
                $tempVar['Answer']=$answer;
                if($typeQuestion->getAttribute('question_type_id')==5){
                    $tempVar['Answer']['title'] = serialize($answer['title']);
                }
                $answerModel = new Answer();
                $answerModel ->load($tempVar);
                $validate_flag = $answerModel->validate() ? $validate_flag : false;
                array_push($allAnswers,   $answerModel);
            }
            //save all models
            if($validate_flag){
                foreach($allAnswers as $answer){
                    $answer->save();
                }
                return $this->actionTest($id);
            }
            return $this->actionTest($id);
        }
        return $this->actionTest($id);
    }

    /**
     * Finds the Question model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Question the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Question::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    /**
     * Finds the Question model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Question the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModelAnswer($id)
    {
        if (($model = Answer::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    /*
        Return array of the question type for dropdown
    */
    protected function getQuestionTypes()
    {
        $query = new Query;
        $query->select('id, description')->from('question_type');
        $types = $query->all();
       
        $all_types = array_column($types, 'description', 'id');
        return $all_types;
    }
    
    /**
     * Creates a new Question model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id)
    {
        $model = new Question();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            //Select form view template according to selected form
            return $this->createAnswerSwitch($model);
        } else {
            return $this->render('create', [
                'model' => $model,
                'all_types' =>$this->getQuestionTypes(),
                'id' => $id
            ]);
        }
    }
    
    /**
     * Creates a new Answer.
     * If creation is successful, the browser will be redirected to the 'create' page.
     * @return mixed
     */
    public function actionAddanswer($id)
    {
        $model = $this->findModel($id);
        $model->answers_cnt=1;
        return $this->createAnswerSwitch($model);
        
    }
    
    /**
     * Switch form tampale when create new answers
     * @param object $model (model of Answer record)
     * @return mixed
     */
    protected function createAnswerSwitch($model){
        switch ($model->questionType->getAttribute('slug')) {
            case 'sympleText':
                return $this->renderingQuestionTypeCreate($model, '_sympletext');
                break;
            case 'sympleImage':
                return $this->renderingQuestionTypeCreate($model, '_sympleimage');
                break;
            case 'textImage':
                return $this->renderingQuestionTypeCreate($model, '_textimage');
                break;
            case 'skinColor':
                return $this->renderingQuestionTypeCreate($model, '_skincolor');
            case 'aboutMeColour':
                return $this->renderingQuestionTypeCreate($model, '_aboutmecolour');
                break;
            case 'aboutMeTwo':
                return $this->renderingQuestionTypeCreate($model, '_aboutmetwo');
                break;
            case 'aboutMeOne':
                return $this->renderingQuestionTypeCreate($model, '_aboutmeone');
                break;
            case 'coloring':
                return $this->renderingQuestionTypeCreate($model, '_coloring');
                break;
            case 'face':
                return $this->renderingQuestionTypeCreate($model, '_face');
                break;
            case 'hair':
                return $this->renderingQuestionTypeCreate($model, '_hair');
                break;
            case 'eyes':
                return $this->renderingQuestionTypeCreate($model, '_hair');
                break;
            case 'user_foto':
                return $this->renderingQuestionTypeUpdate($model, '_user_foto');
                break;
            default:
                $model->delete();
                return $this->redirect(['index']);
                break;
        }
    }

     /**
     * Updates an existing Answers model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdateanswers($id)
    {
        $model = $this->findModel($id);
        return $this->updateAnswerSwitch($model);
    }
    
    /**
     * Switch form tampale when create new answers
     * @param object $model (model of Answer record)
     * @return mixed
     */
    protected function updateAnswerSwitch($model){

views/question/_aboutme.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\widgets\Gallery;


/* @var $this yii\web\View */
/* @var $answers_models */
/* @var $id */
/* $var $isNew*/
?>
<div class="row">
    <div class="col-lg-6 col-lg-offset-3">
<div class="question-form">
    
    <?php $form = ActiveForm::begin(['action' => ['question/' . ($isNew?"save":"update") .'answers/*?id=' . $id],'options' => ['method' => 'post']]); ?>

    <?php 
        $cnt = 1;
        foreach($answers_models as $key => $value){
            echo "Вариант # " . $cnt++; 
            //For id of current record in db. In this case we lose the need to pass this parameter in get request!!!
            echo (!$isNew)? $form->field($value, '[' . $key . ']id')->hiddenInput()->label(false):"";
            echo $form->field($value, '[' . $key . ']question_id')->hiddenInput()->label(false);
            echo $form->field($value, '[' . $key . ']value')->textInput([ 'required' => 'required']);
            $img = is_object($value->mainImage)?$value->mainImage->getAttribute('src'): null;
            echo Gallery::widget(['type' => 'tests', 'idInput' => 'answer-'.$key.'-main_image_id', 'img' => $img]);
            echo $form->field($value, '[' . $key . ']main_image_id')->hiddenInput(['maxlength' => true])->label(false);
            echo $form->field($value, '[' . $key . ']description')->textInput();
            $img = is_object($value->subImage)?$value->subImage->getAttribute('src'): null;
            echo Gallery::widget(['type' => 'tests', 'idInput' => 'answer-'.$key.'-sub_image_id', 'img' => $img]);
            echo $form->field($value, '[' . $key . ']sub_image_id')->textInput();
            echo $form->field($value, '[' . $key . ']buttton_text')->textInput();
            echo "<hr>";
        }
    ?>

    <div class="form-group">
        <?= Html::submitButton( ($isNew?"Create":"Update"), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>
    </div>
    </div>
</div>

views/question/_aboutmecolour.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\widgets\Gallery;
use kartik\select2\Select2;
use yii\web\JsExpression;
use yii\web\View;

/* @var $this yii\web\View */
/* @var $answers_models */
/* @var $id */
/* $var $isNew*/
?>


<?php $form = ActiveForm::begin(['action' => ['question/' . ($isNew ? "save" : "update") . 'answers/*?id=' . $id], 'options' => ['method' => 'post']]); ?>
<div class="row">
    <?php
    $cnt = 1;


    $format = <<< SCRIPT
function format(state) {
    if (!state.id) return state.text;
    var stateId = $('<span style="background-color: '+state.text+';width:90px;height:50px; display:block; color:'+state.text+'; " >' + state.id + '</span>');
    return stateId;
}
SCRIPT;
    $escape = new JsExpression("function(m) { return m; }");
    $this->registerJs($format, View::POS_HEAD);

    foreach ($answers_models as $key => $value) {
        if(!$isNew){
            $data = [];
            foreach (unserialize($value->title) as $item) {
                $data[] = (int)$item;
            }
        }
        echo "<div class='col-md-4 col-md-offset-2'>";
        echo "Вариант # " . $cnt++;
        //For id of current record in db. In this case we lose the need to pass this parameter in get request!!!
        echo (!$isNew) ? $form->field($value, '[' . $key . ']id')->hiddenInput()->label(false) : "";

        echo $form->field($value, '[' . $key . ']question_id')->hiddenInput()->label(false);

        echo $form->field($value, '[' . $key . ']value')->textInput(['required' => 'required']);

        echo $form->field($value, '[' . $key . ']description')->textInput();

        echo $form->field($value, '[' . $key . ']buttton_text')->textInput();
        echo "</div>";
        echo "<div class='col-md-4'>";

        $img = is_object($value->mainImage) ? $value->mainImage->getAttribute('src') : null;
        echo $form->field($value, '[' . $key . ']main_image_id')->hiddenInput(['maxlength' => true])->label("Photo");
        echo Gallery::widget(['type' => 'tests', 'idInput' => 'answer-' . $key . '-main_image_id', 'img' => $img]);

        $color = array('1' => '#efefef', '2' =>'#747474', '3' => '#945858', '4' => '#282828', '5' => '#642554', '6' => '#59945c','7' => '#efefef','8' => '#04e2e5','9' => '#ebdf19','10' => '#ff05c7','11' => '#00610D', '12' => '#282828');
        echo Select2::widget([
            'name' => 'Answer['.$key.'][title]',
            'data' => $color,
            'value' => $data,
            'maintainOrder' => true,
            'language' => 'ru',
            'options' => ['multiple' => true, 'placeholder' => 'Выберите цвета ...','id' => 'answer-' . $key . '-color_id'],
            'pluginOptions' => [
                'maximumSelectionLength' => 6,
                'templateResult' => new JsExpression('format'),
                'templateSelection' => new JsExpression('format'),
                'escapeMarkup' => $escape,
                'allowClear' => true
            ],
        ]);

        echo "</div>";
        echo '<div class="clearfix"></div>';
    }
    ?>
    <div class='col-md-6'>
        <div class="form-group">
            <?= Html::submitButton(($isNew ? "Create" : "Update"), ['class' => 'btn btn-success']) ?>
        </div>
    </div>
    <?php ActiveForm::end(); ?>
</div>

views/question/_aboutmetwo.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\widgets\Gallery;


/* @var $this yii\web\View */
/* @var $answers_models */
/* @var $id */
/* $var $isNew*/
?>
<div class="row">
<div class="question-form">
    
    <?php $form = ActiveForm::begin(['action' => ['question/' . ($isNew?"save":"update") .'answers/*?id=' . $id],'options' => ['method' => 'post']]); ?>

    <?php 
        $cnt = 1;
        foreach($answers_models as $key => $value){
            echo "<div class='col-md-4 col-md-offset-2'>";
                echo "Вариант # " . $cnt++; 
                //For id of current record in db. In this case we lose the need to pass this parameter in get request!!!
                echo (!$isNew)? $form->field($value, '[' . $key . ']id')->hiddenInput()->label(false):"";
                echo $form->field($value, '[' . $key . ']question_id')->hiddenInput()->label(false);
                echo $form->field($value, '[' . $key . ']value')->textInput([ 'required' => 'required']);
                echo $form->field($value, '[' . $key . ']description')->textInput();
                echo $form->field($value, '[' . $key . ']buttton_text')->textInput();
           echo "</div>";
        echo "<div class='col-md-4'>";
            $img = is_object($value->mainImage)?$value->mainImage->getAttribute('src'): null;
            echo $form->field($value, '[' . $key . ']main_image_id')->hiddenInput(['maxlength' => true])->label('Photo #1');
            echo Gallery::widget(['type' => 'tests', 'idInput' => 'answer-'.$key.'-main_image_id', 'img' => $img]);

        

            $img = is_object($value->subImage)?$value->subImage->getAttribute('src'): null;
            echo $form->field($value, '[' . $key . ']sub_image_id')->hiddenInput()->label('Photo #2');
            echo Gallery::widget(['type' => 'tests', 'idInput' => 'answer-'.$key.'-sub_image_id', 'img' => $img]);

            echo "</div>";
            echo '<div class="clearfix"></div>';
        }
    ?>
<div class='col-md-12'>
    <div class="form-group">
        <?= Html::submitButton( ($isNew?"Create":"Update"), ['class' => 'btn btn-success']) ?>
    </div>
</div>

    <?php ActiveForm::end(); ?>
    </div>
</div>

views/question/_coloring.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\widgets\Gallery;

/* @var $this yii\web\View */
/* @var $answers_models */
/* @var $id */
/* $var $isNew*/
?>
<div class="row">
   <div class="question-form">
        <?php $form = ActiveForm::begin(['action' => ['question/' . ($isNew?"save":"update") .'answers/*?id=' . $id],'options' => ['method' => 'post']]); ?>

        <?php 
            $cnt = 1;
            foreach($answers_models as $key => $value){
                 
                if($cnt==1){
                    echo '<div class="col-md-offset-4 col-md-4">';
                    echo $form->field($value, '[' . $key . ']title')->dropDownList([''=>'Default', 'colr-1'=>'Темный колорит','colr-2'=>'Холодный колорит', 'colr-3'=>'Теплый колорит' ,'colr-4'=>'Мягкий колорит'])->label("Color for frame");
                    echo "</div><br><br><br><br><br>";
                    echo '<div class="clearfix"></div>';
                }
               
                
                echo '<div class="col-md-4 col-md-offset-4">';
                    echo "Вариант # " . $cnt++; 
                    //For id of current record in db. In this case we lose the need to pass this parameter in get request!!!
                        echo (!$isNew)? $form->field($value, '[' . $key . ']id')->hiddenInput()->label(false):"";
                        echo $form->field($value, '[' . $key . ']question_id')->hiddenInput()->label(false);
                        echo $form->field($value, '[' . $key . ']value')->textInput([ 'required' => 'required']);
                        echo $form->field($value, '[' . $key . ']buttton_text')->textInput();
                       
                    echo "</div>";
                    echo '<div class="col-md-4">';
                        $img = is_object($value->mainImage)?$value->mainImage->getAttribute('src'): null;
                        echo Gallery::widget(['type' => 'tests', 'idInput' => 'answer-'.$key.'-main_image_id', 'img' => $img]);
                        echo $form->field($value, '[' . $key . ']main_image_id')->hiddenInput(['maxlength' => true])->label(false);
                    echo "</div>";
                    echo '<div class="clearfix"></div>';
            }
        ?>

        <div class='col-md-6'>
            <div class="form-group">
                <?= Html::submitButton( ($isNew?"Create":"Update"), ['class' => 'btn btn-success']) ?>
            </div>
         </div>

        <?php ActiveForm::end(); ?>
    </div>
</div>

views/question/_face.php
<?php
    use yii\helpers\Html;
    use yii\widgets\ActiveForm;
    use common\widgets\Gallery;


    /* @var $this yii\web\View */
    /* @var $answers_models */
    /* @var $id */
    /* $var $isNew*/
?>
<div class="row">

        <?php $form = ActiveForm::begin(['action' => ['question/' . ($isNew?"save":"update") .'answers/*?id=' . $id],'options' => ['method' => 'post']]); ?>

        <?php 
            $cnt = 1;
            foreach($answers_models as $key => $value){
                echo "<div class='col-md-4 col-md-offset-4'>";
                echo "Вариант # " . $cnt++; 
                //For id of current record in db. In this case we lose the need to pass this parameter in get request!!!
                echo (!$isNew)? $form->field($value, '[' . $key . ']id')->hiddenInput()->label(false):"";
                echo $form->field($value, '[' . $key . ']question_id')->hiddenInput()->label(false);

                echo $form->field($value, '[' . $key . ']value')->textInput([ 'required' => 'required']);
                echo "<hr>";
                echo "</div>";

                echo "<div class='col-md-3'>";
                    $img = is_object($value->mainImage)?$value->mainImage->getAttribute('src'): null;
                    echo Gallery::widget(['type' => 'tests', 'idInput' => 'answer-'.$key.'-main_image_id', 'img' => $img]);
                    echo $form->field($value, '[' . $key . ']main_image_id')->hiddenInput(['maxlength' => true])->label(false);
                echo "</div>";
                echo '<div class="clearfix"></div>';
            }
        ?>
    <div class='col-md-3'>
        <div class="form-group">
            <?= Html::submitButton( ($isNew?"Create":"Update"), ['class' => 'btn btn-success']) ?>
        </div>
    </div>
        <?php ActiveForm::end(); ?>
    
</div>

views/question/_hair.php
<?php
    use yii\helpers\Html;
    use yii\widgets\ActiveForm;
    use common\widgets\Gallery;


    /* @var $this yii\web\View */
    /* @var $answers_models */
    /* @var $id */
    /* $var $isNew*/
?>
<div class="row">
        <?php $form = ActiveForm::begin(['action' => ['question/' . ($isNew?"save":"update") .'answers/*?id=' . $id],'options' => ['method' => 'post']]); ?>

        <?php 
            $cnt = 1;
            $switchTree=false;
            $cntRow=1;
            $cntThree=1;
            
            $offsetDown=0;
            $cntAnswers=count($answers_models);

            foreach($answers_models as $key => $value){
                if($switchTree){
                    echo '<div class="clearfix"></div>';
                    $switchTree=false;
                }


                if(($cntAnswers/4)>=($cnt))
                {
                    $childcnt = 1;
                    $parentcnt = 1;
                    echo "<div class='col-md-1'>";
                    echo "Вариант № " . $cnt++;
                    //For id of current record in db. In this case we lose the need to pass this parameter in get request!!!
                    echo (!$isNew)? $form->field($value, '[' . $key . ']id')->hiddenInput()->label(false):"";
                    echo $form->field($value, '[' . $key . ']question_id')->hiddenInput()->label(false);
                    echo $form->field($value, '[' . $key . ']value')->hiddenInput([ 'value'=>$cnt-1])->label(false);

                    $img = is_object($value->mainImage)?$value->mainImage->getAttribute('src'): null;
                    echo Gallery::widget(['type' => 'tests', 'idInput' => 'answer-'.$key.'-main_image_id', 'img' => $img]);
                    echo $form->field($value, '[' . $key . ']main_image_id')->hiddenInput(['maxlength' => true])->label(false);

                    echo "</div>";
                    if(($cntAnswers/4)<($cnt)){
                        $offsetDown++;
                        $switchTree=true;
                    }
                }
                else{
                    if($cntThree==1){
                        if(($offsetDown+3)>($cntAnswers/4)){
                            $offsetDownCorection =($cntAnswers/4)-2;
                        }
                        else{
                             $offsetDownCorection= $offsetDown;
                        }
                        for($i=$offsetDownCorection; $i>1; $i--){

                            echo "<div class='col-md-1'></div>";
                        }
                    }

                    if($cntThree<4){

                        $cntThree++;
                        echo "<div class='col-md-1'>";
                        echo "Вариант № ".$parentcnt.'.' . $childcnt++;
                        //For id of current record in db. In this case we lose the need to pass this parameter in get request!!!
                        echo (!$isNew)? $form->field($value, '[' . $key . ']id')->hiddenInput()->label(false):"";
                        echo $form->field($value, '[' . $key . ']question_id')->hiddenInput()->label(false);
                        echo $form->field($value, '[' . $key . ']value', [ 'options' => [ 'style' => 'display: none']])->textInput(['type' => 'number', 'value'=> $parentcnt.'.' . ($childcnt-1)])->label(false);
                        $img = is_object($value->mainImage)?$value->mainImage->getAttribute('src'): null;
                        echo Gallery::widget(['type' => 'tests', 'idInput' => 'answer-'.$key.'-main_image_id', 'img' => $img]);
                        echo $form->field($value, '[' . $key . ']main_image_id')->hiddenInput(['maxlength' => true])->label(false);

                        echo "</div>";
                    }

                    if($cntThree>3){
                        $parentcnt++;
                        $childcnt = 1;
                        $switchTree=true;
                        $offsetDown++;
                        $cntThree=1;
                    }
                }
            }
        ?>
    <div class="clearfix"></div>
    <div class='col-md-3'>
        <div class="form-group">
            <?= Html::submitButton( ($isNew?"Create":"Update"), ['class' => 'btn btn-success']) ?>
        </div>
    </div>
        <?php ActiveForm::end(); ?>
</div>
<style>
    .btn-warning{
        font-size: 11px;
        padding-left: 6px;
    }
</style>

views/question/_search.php
<?php
    use yii\helpers\Html;
    use yii\widgets\ActiveForm;

    /* @var $this yii\web\View */
    /* @var $model common\models\database\QuestionSearch */
    /* @var $form yii\widgets\ActiveForm */
?>

<div class="question-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'test_id') ?>

    <?= $form->field($model, 'question_type_id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'subtitle') ?>

    <?php // echo $form->field($model, 'priority') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/question/_textimage.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\widgets\Gallery;

/* @var $this yii\web\View */
/* @var $answers_models */
/* @var $id */
/* $var $isNew*/

?>
<div class="row">
    <div class="col-lg-6 col-lg-offset-3">
<div class="question-form">
    
    <?php $form = ActiveForm::begin(['action' => ['question/' . ($isNew?"save":"update") .'answers/*?id=' . $id],'options' => ['method' => 'post']]); ?>

    <?php 
        $cnt = 1;
        foreach($answers_models as $key => $value){
            echo "Вариант № " . $cnt++;
            //For id of current record in db. In this case we lose the need to pass this parameter in get request!!!
            echo (!$isNew)? $form->field($value, '[' . $key . ']id')->hiddenInput()->label(false):"";
            
            echo $form->field($value, '[' . $key . ']question_id')->hiddenInput()->label(false);
            
            echo $form->field($value, '[' . $key . ']value')->textInput([ 'required' => 'required'])->label('Value(yes)');

            echo $form->field($value, '[' . $key . ']description')->textarea(['rows'=>3, 'required' => 'required']);

            $img = is_object($value->mainImage)?$value->mainImage->getAttribute('src'): null;
            echo Gallery::widget(['type' => 'tests', 'idInput' => 'answer-'.$key.'-main_image_id', 'img' => $img]);

            echo $form->field($value, '[' . $key . ']main_image_id')->hiddenInput(['maxlength' => true])->label(false);

            echo "<hr>";
        }
    ?>

    <div class="form-group">
        <?= Html::submitButton( ($isNew?"Create":"Update"), ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>
    </div>
    </div>
</div>

views/question/_user_foto.php
<?php
use yii\helpers\Html;

echo Html::a('К вопросам' , ['question/test', 'id' => $_GET['id']] , ['class' => 'btn btn-success']);

views/question/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\database\QuestionSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */
/* @var $id */

$this->title = 'Questions';
$this->params['breadcrumbs'][] = $this->title;
$this->beginBlock('content-header');
echo $this->title;
$this->endBlock();
?>
<div class="question-index">
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <div class="box box-success">
        <div class="box-header with-border">
            <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
            <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            </div>
        </div>
        <div class="box-body">
            <p>

                <?php if (isset($id) && $id) {
                    echo Html::a('Добавить вопрос к тесту №' . $id, ['question/create', 'id' => $id], ['class' => 'btn btn-success']);
                } ?>
            </p>
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],
                    'id',
                    'title:ntext',
                    ['attribute' => 'test_id',
                        'format' => 'raw',
                        'label' => 'Test',
                        'value' => function ($model) {
                            $result = '';
                            if (is_object($model->test)) {
                                $result = $model->test->getAttribute('title');
                            }
                            return $result;
                        }
                    ],
                    ['attribute' => 'question_type_id',
                        'format' => 'raw',
                        'label' => 'Question Type',
                        'value' => function ($model) {
                            $result = '';
                            if (is_object($model->questionType)) {
                                $result = $model->questionType->getAttribute('description');
                            }
                            return $result;
                        }
                    ],
                    //'subtitle:ntext',
                    'priority',

                    ['class' => 'yii\grid\ActionColumn'],
                ],
            ]); ?>
        </div>
    </div>