controllers/TestController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\database\Test;
use common\models\database\TestReferences;
use common\models\database\TestReferencesSearch;
use common\models\search\Test as TestSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use common\models\database\Gallery;
use common\models\main\StringModel;

/**
 * TestController implements the CRUD actions for Test model.
 */
class TestController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actions(){
        if(Yii::$app->user->isGuest){
            $this->redirect(['user/security/login']);
        }
    }

    /**
     * Lists all Test models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new TestSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Test model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Test model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Test();

        if ($model->load(Yii::$app->request->post())) {
            $model->alias = StringModel::str2url($model->title);
            $model->updated_at = strtotime($model->updated_at);
            $model->created_at = strtotime($model->created_at);
            $model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'img'   => null,
            ]);
        }
    }
    
    /**
     * Creates a new Test model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionAddreftest()
    {
        $model = new TestReferences();
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
             return $this->redirect(['update', 'id' => Yii::$app->request->post('TestReferences')['test_parrent_id']]);
        } else {
             return $this->redirect(['update', 'id' => Yii::$app->request->post('TestReferences')['test_parrent_id']]);
        }
    }

    /**
     * Updates an existing Test model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
    */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $searchModel = new TestReferencesSearch();
        $searchModel->test_parrent_id=$id;
        $dataProvider = $searchModel->search(['sort'=>'position']);
        $referenceModel = new TestReferences();
        $referenceModel->setAttribute('test_parrent_id', $id);

        if ($model->load(Yii::$app->request->post())) {
            $model->alias = StringModel::str2url($model->title);
            $model->updated_at = strtotime($model->updated_at);
            $model->created_at = strtotime($model->created_at);
            $model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'img' => Gallery::findOne(['id' => $model->img])->src,
                'dataProviderReference' => $dataProvider,
                'referenceModel' => $referenceModel
            ]);
        }
    }

    /**
     * Deletes an existing Test model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Deletes an existing TestReferences model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
    */
    public function actionDeletechildtest($id)
    {
        $model = $this->findModelReference($id);
        $test_parrent_id = $model->getAttribute('test_parrent_id');
        $model->delete();
        return $this->redirect(['update', 'id' => $test_parrent_id]);
    }

    /**
     * Finds the Test model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Test the loaded model
     * @throws NotFoundHttpException if the model cannot be found
    */
    protected function findModel($id)
    {
        if (($model = Test::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

     /**
     * Finds the TestReferences model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return TestReferences the loaded model
     * @throws NotFoundHttpException if the model cannot be found
    */
    protected function findModelReference($id)
    {
        if (($model = TestReferences::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/TestValuesController.php
<?php

namespace backend\controllers;

use common\models\database\Test;
use Yii;
use common\models\database\TestValues;
use common\models\database\TestValuesSearch;
use common\models\database\TestValuesMatrix;
use common\models\database\TestValuesMatrixSearch;
use common\models\database\Question;
use yii\base\DynamicModel;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Url;

/**
 * TestValuesController implements the CRUD actions for TestValues model.
 */
class TestValuesController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete'        => ['POST'],
                    'blockmatrix'   => ['POST'],
                    'deletematrix'  => ['POST']
                ],
            ],
        ];
    }

    /**
     * Lists all TestValues models.
     * @return mixed
     */
//    public function actionIndex()
//    {
//        $searchModel = new TestValuesSearch();
//        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
//
//        return $this->render('index', [
//            'searchModel' => $searchModel,
//            'dataProvider' => $dataProvider,
//        ]);
//    }

    /**
     * Displays a single TestValues model.
     * @param integer $id
     * @return mixed
     */
//    public function actionView($id)
//    {
//        return $this->render('view', [
//            'model' => $this->findModel($id),
//        ]);
//    }

    /**loadMultiple yii2
     * Creates a new TestValues model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
    */
    public function actionCreate($id)
    {
        $newModel = new TestValues();
        $newModel->setAttribute('test_id', $id);
        $model = TestValues::find()->where(['=', "test_id", $id])->all();

        //matrix model
        $searchModelMatrix = new TestValuesMatrixSearch();
        $searchModelMatrix->test_id=$id;
        $dataProviderMatrix = $searchModelMatrix->search(Yii::$app->request->queryParams);

        //creating dinamic model for creatin matrix
        $matrixModel = DynamicModel::validateData(array('question_horizontal_id', 'question_vertical_id'), [
                             [['question_horizontal_id', 'question_vertical_id'], 'required', 'skipOnEmpty'=>true],
                             [['question_horizontal_id', 'question_vertical_id'], 'integer'],
                             [['question_horizontal_id'], 'compare', 'compareAttribute'=>'question_vertical_id', 'operator'=>'!='],
                             [['question_vertical_id'], 'compare', 'compareAttribute'=>'question_horizontal_id', 'operator'=>'!=']
                        ]);

        if(Yii::$app->request->post()){
            $validate_flag = true;
            $allTempModels=[];

            foreach (Yii::$app->request->post('TestValues') as $testValues ){
                $tempVar['TestValues']=$testValues;
                if($testValues['id']){
                    $modelTestValues =  $this->findModel($testValues['id']);
                    $modelTestValues->load($tempVar);

                }
                else{
                     $modelTestValues =  clone $newModel;
                     $modelTestValues->load($tempVar);
                }

                $validate_flag = $modelTestValues->validate() ? $validate_flag : false;
                array_push($allTempModels,   $modelTestValues);
            }
            
           if($validate_flag){
                foreach($allTempModels as $tempModel){
                    $tempModel->save();
                }
            }

            return $this->render('create', [
                   'model' => $allTempModels,
                   'matrixModel' => $matrixModel,
                   'searchModelMatrix' => $searchModelMatrix,
                   'dataProviderMatrix' =>$dataProviderMatrix
               ]);
        } else {
            $model = $model ? $model : array($newModel);

            return $this->render('create', [
                'model' => $model,
                'matrixModel' => $matrixModel,
                'searchModelMatrix' => $searchModelMatrix,
                'dataProviderMatrix' =>$dataProviderMatrix
            ]);
        }
    }

    /**Create matrix for test result
     * Creates a new TestValues model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
    */
    public function actionCreatematrix(){        
        if(Yii::$app->request->post('DynamicModel')){
            $questionH = Question::findOne(Yii::$app->request->post('DynamicModel')['question_horizontal_id']);
            $questionV = Question::findOne(Yii::$app->request->post('DynamicModel')['question_vertical_id']);

            $cntAnswersH  = count($questionH->answers);
            $cntAnswersOffsetH = (int)($cntAnswersH/4);
            $cntAnswersV  = count($questionV->answers);
            $cntAnswersOffsetV = (int)($cntAnswersV/4);

            for($i=$cntAnswersOffsetV; $i<$cntAnswersV; $i++){
                for($j=$cntAnswersOffsetH; $j<$cntAnswersH; $j++){
                   $ownModel["{$questionV->answers[$i]->getAttribute('value')}"]["{$questionH->answers[$j]->getAttribute('value')}"]=0;
                }
            }

            return $this->render('creatematrix', [
                'ownModel' => $ownModel,
                'questionH' => $questionH,
                'questionV' => $questionV,
                'testValues' => TestValues::getTestValues($questionH->getAttribute('test_id')),
            ]);
        }

        //creating and save matrix
        if(Yii::$app->request->post('TestValuesMatrix')){
            $testValuesMatrix = new TestValuesMatrix();

            //var_dump(Yii::$app->request->post('TestValuesMatrix'));
            $myPost['TestValuesMatrix'] = Yii::$app->request->post('TestValuesMatrix');
            $myPost['TestValuesMatrix']['serialize'] = serialize($myPost['TestValuesMatrix']['serialize']);
            
            //check if it's a first matrix for test
            $Allmatrixes = TestValuesMatrix::find()->where(['and', "test_id=" . $myPost['TestValuesMatrix']['test_id']])->all();
            
            $model = new TestValuesMatrix();
            
            if(!$Allmatrixes){
                $model->setAttribute('active_flag', 1);
            }
            
            if ($model->load($myPost) && $model->save()) {
                return $this->redirect(['create', 'id' => $model->test_id]);
            } else {
                $questionH = Question::findOne(Yii::$app->request->post('TestValuesMatrix')['question_horizontal_id']);
                $questionV = Question::findOne(Yii::$app->request->post('TestValuesMatrix')['question_vertical_id']);
                return $this->render('creatematrix', [
                    'ownModel' => Yii::$app->request->post('TestValuesMatrix')['serialize'],
                    'questionH' => $questionH,
                    'questionV' => $questionV,
                    'testValues' => TestValues::getTestValues($questionH->getAttribute('test_id')),
                ]);
            }
        }
    }

    /**
     * Updates an existing TestValuesMatrix model.
     * If update is successful, the browser will be redirected to the 'create' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModelMatrix($id);
        if (Yii::$app->request->post()) {
            //if ($model->load(Yii::$app->request->post()) && $model->save()) 
            $myPost['TestValuesMatrix'] = Yii::$app->request->post('TestValuesMatrix');
            $myPost['TestValuesMatrix']['serialize'] = serialize($myPost['TestValuesMatrix']['serialize']);
            
            if ($model->load($myPost) && $model->save()) {
                return $this->redirect(['create', 'id' => $model->test_id]);
            } else {
                return $this->render('updatematrix', [
                    'ownModel' => Yii::$app->request->post('TestValuesMatrix')['serialize'],
                    'questionH' => $model->questionHorizontal,
                    'questionV' => $model->questionVertical,
                    'testValues' => TestValues::getTestValues($questionH->getAttribute('test_id')),
                ]);
            }

        } else {
            return $this->render('updatematrix', [
                 'ownModel' => unserialize($model->getAttribute('serialize')),
                 'questionH' => $model->questionHorizontal,
                 'questionV' => $model->questionVertical,
                 'testValues' => TestValues::getTestValues($model->getAttribute('test_id')),
            ]);
        }
    }

     /**
     * Change matrix active flag
     * If update is successful, the browser will be redirected to the 'create' page.
     * @param integer $id
     * @return mixed
     */
    public function actionBlockmatrix($id){

        $matrix  = $this->findModelMatrix($id);
        if ($matrix->getAttribute('active_flag')) {
            $matrix->setAttribute('active_flag', 0);
            $matrix->save();
            Yii::$app->getSession()->setFlash('success','Matrix has been inactivated');
        } else {
            $Allmatrixes = TestValuesMatrix::find()->where(['and', "test_id=" . $matrix->getAttribute('test_id'), "id<>" . $matrix->getAttribute('id')])->all();

            foreach($Allmatrixes as $model){
                if($model->getAttribute('active_flag')){
                    $model->setAttribute('active_flag', 0);
                    $model->save();
                }
            }

            $matrix->setAttribute('active_flag', 1);
            $matrix->save();

views/test-values/_form.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use common\models\database\Test;
use mihaildev\ckeditor\CKEditor;
use yii\grid\GridView;
use yii\widgets\Pjax;

/* @var $this yii\web\View */
/* @var $model common\models\database\TestValues */
/* @var $form yii\widgets\ActiveForm */
/* @var $matrixModel yii\base\DynamicModel */

$formCnt = 0;
$result_type = Test::findOne($_GET['id'])->getAttribute('result_type_id');
?>

    <div class="test-values-form">

        <?php $form = ActiveForm::begin(['enableClientValidation' => false]);
        foreach ($model as $key => $mod):
            $formCnt++;
            ?>

            <div class="form_section" data-testvalue="<?= $mod->getAttribute('id') ?>">
                <div class="row">

                    <?= Html::hiddenInput('TestValues[' . $key . ']test_id', $mod->getAttribute('test_id')); ?>
                    <div>
                        <?= $form->field($mod, '[' . $key . ']id')->hiddenInput()->label(false) ?>
                    </div>
                    <?php if ($result_type == 1): ?>
                        <div class="col-md-2 col-lg-1">
                            <?= $form->field($mod, '[' . $key . ']from')->textInput(['required' => 'required', 'type' => 'number', 'step' => '0.01']) ?>
                        </div>
                        <div class="col-md-2 col-lg-1">
                            <?= $form->field($mod, '[' . $key . ']to')->textInput(['required' => 'required', 'type' => 'number', 'step' => '0.01']) ?>
                        </div>
                    <?php endif; ?>
                    <?php if ($result_type == 4): ?>
                        <div class="col-md-2 col-lg-1">
                            <?= $form->field($mod, '[' . $key . ']from')->textInput(['required' => 'required', 'type' => 'number', 'step' => '0.01'])->label('Значение') ?>
                        </div>
                    <?php endif; ?>
                    <div
                        class="col-md-<?= $result_type == 1 ? 3 : ($result_type == 1 || $result_type == 4) ?> col-lg-<?= ($result_type == 1 || $result_type == 4) ? 3 : 3 ?>">
                        <?= $form->field($mod, '[' . $key . ']answer')->textInput(['required' => 'required']) ?>
                    </div>
                    <div class="col-md-<?= $result_type == 1 ? 3 : 5 ?> col-lg-<?= $result_type == 1 ? 3 : 4 ?>">
                        <?= $form->field($mod, '[' . $key . ']query_values')->textarea(['rows' => 1, 'required' => 'required']) ?>
                    </div>
                    <div class="col-md-<?= $result_type == 1 ? 3 : 5 ?> col-lg-<?= $result_type == 1 ? 3 : 4 ?>">
                        <?= $form->field($mod, '[' . $key . ']query_colors')->textarea(['rows' => 1]) ?>
                    </div>
                    <div class="col-md-1 col-lg-1">
                        <br>
                        <a class="btn btn-xs btn-success btn-block"
                           href="https://imagecorp.ru/demo/result/?id=<?= $mod->id ?>&view=demo"
                           target="_blank">Просмотр</a>
                        <?=
                        Html::a(Yii::t('user', 'Delete'), ['test-values/delete', 'id' => $mod->id], [
                            'class' => 'btn btn-xs btn-danger btn-block delete_button'
                        ]);
                        ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2 col-lg-2 col-md-offset-5 col-lg-offset-5">
                        <a data-toggle="collapse" class="btn btn-xs btn-success btn-block"
                           data-target="#collapse<?= $key ?>">Page</a>
                    </div>
                </div>
                <div id="collapse<?= $key ?>" class="collapse">
                    <div class="row">
                        <div class="col-md-12 col-lg-12">
                            <? //= $form->field($mod, '[' . $key . ']page_title')->textInput()
                            ?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 col-lg-12">
                            <?=
                            $form->field($mod, '[' . $key . ']page_description')->widget(CKEditor::className(), [
                                'editorOptions' => [
                                    'preset' => 'full', //разработанны стандартные настройки basic, standard, full данную возможность не обязательно использовать
                                    'inline' => false, //по умолчанию false
                                    'clientOptions' => [
                                        'allowedContent' => TRUE,
                                    ],
                                ],
                            ])->label('Page content');; ?>
                            ?>

                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>

        <br>
        <div class="row" id="new_section">
            <div class="col-md-2 col-md-offset-5">
                <a id="add_new" class="btn btn-xs btn-success btn-block">Add new Test result</a>
            </div>
        </div>
        <div class="form-group"><br>
            <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
        </div>
        <?php ActiveForm::end(); ?>

        <br>
        <br>
    </div>

<?php
// && !$model[0]->isNewRecord
?>
<?php if ($result_type == 2): ?>
    <h2>Матрицы</h2>
    <?php
    // if questions quantity more than 2
    if (count($model[0]->test->question) > 1):
        Pjax::begin();

        echo GridView::widget([
            'dataProvider' => $dataProviderMatrix,
            'filterModel' => $searchModelMatrix,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],

                'id',
                [
                    'label' => 'Vertical Question',
                    'format' => 'raw',
                    'value' => function ($data) {
                        $result = "";
                        if ($data->questionHorizontal) {
                            $result = $data->questionVertical->getAttribute('subtitle');
                        }
                        return $result;
                    },
                ],
                [
                    'label' => 'Horizontal Question',
                    'format' => 'raw',
                    'value' => function ($data) {
                        $result = "";
                        if ($data->questionHorizontal) {
                            $result = $data->questionHorizontal->getAttribute('subtitle');
                        }
                        return $result;
                    },
                ],
                'question_vertical_id',
                // 'serialize:ntext',
                // 'active_flag',
                [
                    'header' => 'Active',
                    'format' => 'raw',
                    'value' => function ($model) {
                        if (!$model->active_flag) {
                            return Html::a('Active', ['blockmatrix', 'id' => $model->id], [
                                'class' => 'btn btn-xs btn-success btn-block',
                                'data-method' => 'post',
                                'data-confirm' => 'Are you sure you want to active this matrix?',
                            ]);
                        } else {
                            return "<div class='btn btn-xs btn-danger btn-block'>Inactive</div>";
                        }
                    },
                    'format' => 'raw',
                ],
                [
                    'class' => 'yii\grid\ActionColumn',
                    'template' => '{update}{delete}',
                    'contentOptions' => ['class' => 'table_buttons'],
                    'buttons' => [
                        'delete' => function ($url, $model) {
                            return Html::a('<span class="glyphicon glyphicon-trash"></span>', ['deletematrix', 'id' => $model->id], ['title' => 'Delete', 'data' => ['confirm' => 'Are you sure you want to delete this item?', 'method' => 'post'], 'data-ajax' => '1', 'class' => 'modificator']);
                        },
//                                'usersportfolio' => function ($url, $model) {
//                                    return Html::a('<span class="glyphicon glyphicon-book"></span>', Yii::$app->getUrlManager()->getBaseUrl() . '/portfolio/usersportfolio/'. $model->getAttribute('id'), ['title' => Yii::t('app', 'Portfolios')]);
//                                },
//                               'usershonours' => function ($url, $model) {
//                                    return Html::a('<span class="glyphicon glyphicon-list"></span>', ['user-honours/usershonours', 'id' => $model->id], ['title' => Yii::t('app', 'Honours')]);
//                                },
//                                'usersvideos' => function ($url, $model) {
//                                    return Html::a('<span class="glyphicon glyphicon-play"></span>', ['user-videos/usersvideos', 'id' => $model->id], ['title' => Yii::t('app', 'Videos')]);
//                                },
                    ],
                ],
            ],
        ]);
        Pjax::end();
        $formMatrix = ActiveForm::begin(['action' => ['test-values/creatematrix'], 'options' => ['method' => 'post']]);
        ?>
        <div class="row">
            <div class="col-md-3 col-lg-3">
                <?= $formMatrix->field($matrixModel, 'question_horizontal_id')->dropDownList($model[0]->questions, ['prompt' => 'Выберите вопрос...']); ?>
            </div>
            <div class="col-md-3 col-lg-3">
                <?= $formMatrix->field($matrixModel, 'question_vertical_id')->dropDownList($model[0]->questions, ['prompt' => 'Выберите вопрос...']); ?>
            </div>
            <div class="col-md-3 col-lg-3">
                <br>
                <?= Html::submitButton('Add +', ['class' => 'btn btn-success']) ?>
            </div>
        </div>
        <?php
        ActiveForm::end();
    endif;
    ?>
<?php endif; ?>
    <script>
        var formCnt = <?= $formCnt ?>
    </script>
<?php
$js = <<<JS

        CKEDITOR.config.allowedContent = true;
        CKEDITOR.config.removeFormatAttributes = '';

JS;
$this->registerJs($js, \yii\web\View::POS_END);

views/test-values/_formmatrix.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\Pjax;

/* @var $ownModel */
/* @var $questionH \common\models\database\Question; */
/* @var $questionV \common\models\database\Question;*/
/* @var $testValues */
?>
<style>
.verticalText {
  -webkit-transform: rotate(-90deg);
  -moz-transform: rotate(-90deg);
  -ms-transform: rotate(-90deg);
  -o-transform: rotate(-90deg);
  transform: rotate(-90deg);
  filter: progid: DXImageTransform.Microsoft.BasicImage(rotation=3);
}
</style>
  
<div class="table-responsive">
    <?php $form = ActiveForm::begin(['enableClientValidation'=>false]); ?>

    <?= Html::hiddenInput('TestValuesMatrix[question_vertical_id]',   $questionV->getAttribute('id')); ?>
    <?= Html::hiddenInput('TestValuesMatrix[question_horizontal_id]', $questionH->getAttribute('id')); ?>
    <?= Html::hiddenInput('TestValuesMatrix[test_id]', $questionV->getAttribute('test_id')); ?>


<table class="table">
    <tr>
        <th></th>
        <th style="text-align: center;" colspan="<?= count(array_values($ownModel)[0]) ?>" ><?= $questionH->getAttribute('subtitle')?></th>
    </tr>
    <tr>
       <th></th>
       <th></th>
        <?php
            foreach (array_values($ownModel)[0] as $key => $value) {
                echo  "<th>{$key}</th>";
            }
        ?>
    </tr>
        <?php 
            $cnt= 0; 
            foreach ($ownModel as $key => $value) {

                if(!$cnt):?>
                <th class ="rotate" rowspan="<?= count($ownModel) + 1 ?>"><div class="verticalText"><?= $questionV->getAttribute('subtitle')?></div></th>
                <?php $cnt++;
                endif;

                echo "<tr><th>{$key}</th>";

                foreach ($value as $k => $v){
                    echo  "<td>".  Html::dropDownList('TestValuesMatrix[serialize][' .$key . '][' . $k . ']', $v, $testValues, ['class' => 'form-control']) . "</td>";
                }
                echo "</tr>";
            }
        ?>
</table>
    <?= Html::submitButton('Save' , ['class' => 'btn btn-success']) ?>
    <?php ActiveForm::end(); ?>
</div>

views/test-values/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model common\models\database\TestValues */
/* @var $matrixModel yii\base\DynamicModel */

$this->registerJsFile('js/createTestValues.js', ['depends' => 'backend\assets\AppAsset']);

$this->title = 'Test\'s values';
$this->params['breadcrumbs'][] = ['label' => 'All Tests', 'url' => ['test/index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box box-success">
    <div class="box-header with-border">
        <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
        <div class="box-tools pull-right">
            <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
        </div>
    </div>
    <div class="box-body">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= 

        $this->render('_form', [
        'model' => $model,
        'matrixModel' => $matrixModel,
        'searchModelMatrix' => $searchModelMatrix,
        'dataProviderMatrix' =>$dataProviderMatrix
    ]) ?>

    </div>
</div>

views/test-values/creatematrix.php
<?php

use yii\helpers\Html;

/* @var $ownModel */
/* @var $questionH \common\models\database\Question; */
/* @var $questionV \common\models\database\Question;*/
/* @var $testValues */
?>
<?php 
    $this->title = 'Create matrix';
    $this->params['breadcrumbs'][] = ['label' => 'All Tests', 'url' => ['test/index']];
    $this->params['breadcrumbs'][] = ['label' => 'Test\'s values', 'url' => ['test-values/create', 'id'=>$questionH->getAttribute('test_id')]];
    $this->params['breadcrumbs'][] = $this->title;
?>

<div class="box box-success">
    <div class="box-header with-border">
        <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
        <div class="box-tools pull-right">
            <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
        </div>
    </div>
    <div class="box-body">
        <?= $this->render('_formmatrix', [
            'ownModel' => $ownModel,
            'questionH' =>$questionH,
            'questionV' =>$questionV,
            'testValues' =>$testValues,
        ]) ?>
    </div>
</div>

views/test-values/updatematrix.php
<?php

use yii\helpers\Html;

/* @var $ownModel */
/* @var $questionH \common\models\database\Question; */
/* @var $questionV \common\models\database\Question;*/
/* @var $testValues */
?>
<?php 
    $this->title = 'Create matrix';
    $this->params['breadcrumbs'][] = ['label' => 'All Tests', 'url' => ['test/index']];
    $this->params['breadcrumbs'][] = ['label' => 'Test\'s values', 'url' => ['test-values/create', 'id'=>$questionH->getAttribute('test_id')]];
    $this->params['breadcrumbs'][] = $this->title;
?>
<div class="box box-success">
    <div class="box-header with-border">
        <h3 class="box-title"><?= Html::encode($this->title) ?></h3>
        <div class="box-tools pull-right">
            <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
        </div>
    </div>
    <div class="box-body">

    <?= $this->render('_formmatrix', [
        'ownModel' => $ownModel,
        'questionH' =>$questionH,
        'questionV' =>$questionV,
        'testValues' =>$testValues,
    ]) ?>

    </div>
</div>